# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0d181c8368b59f48cec299b33a687051fe1d70ca86bbb3def8a8823ca88f614ad9f782b978ca6b774018942c38141896a50352f61f91516002a9ac8dc6846ef8

test:
  secret_key_base: eb2a8b631590d304b7306c2cd07ed4bc55fe18998cb0eaa1ddceab7b19c6ae8fd0caffd4280038d12b44cbfafcb29cd8d6a2aed3fd751a36bf8ddebaee2702c7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
